//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace Assessment.Library
{
    using System;
    using System.Collections.Generic;

    public partial class CompanyDetail
    {
        public int Id { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> Total_Employees { get; set; }
        public string Goal { get; set; }
        public Nullable<int> ClientTypeId { get; set; }
        public Nullable<int> W_Employees { get; set; }
        public Nullable<int> M_Employees { get; set; }
        public string Year { get; set; }
        public Nullable<int> CompanyId { get; set; }

        public virtual Client Client { get; set; }
        public virtual Company Company { get; set; }
        [NotMapped]
        public decimal? Ratio { get; set; }
    }
}
